<?php 	$pageTitle = "Impacto &#9119; APOD";	$menuItem = "impact";	$englishPage = "impact.php";	include('inc/esheader.php'); ?><div class="container">			<!-- INCEPTION 			================================================== -->			<div class="sixteen columns">								<div class="textBox-display add-bottom dropshadowOrange red-orange corner-round">										<h3 class="oswald edit-txt" id="n0">Impacto</h3>										<h5 class=" edit-txt" id="n1">											Desde su creación en 2007, AP ha entrenado a más de 1,000 facilitadores en más de 400 organizaciones que sirven la familia y ha proporcionado su plan de estudios a más de 30,000 padres / familias en 256 ciudades de todo el país.					</h5>				</div>						<!-- MAP 			====================================== -->						<img src="images/maplocations.jpg" class="scale-with-grid2 add-bottom">				<!-- NATIONAL EVALUATION -->										<h5 class="ruled remove-bottom google light-blue edit-txt" id="n2">Evaluación Nacional</h5>															<div class="textBox edit" id="n3"><p>En el 2012, una evaluación nacional independiente de Abriendo Puertas / Opening Doors conducida por el Dr. Bruce Fuller y Dr. Margaret Bridges de la Universidad de Berkeley encontró que los padres participantes hicieron avances significativos en el conocimiento del desarrollo de la niñez temprana y la paternidad. Estos conocimientos ganados ayudaron a los padres a aumentar su auto-confianza, sus habilidades de criar a sus hijos y a abogar por sus familias. (Bridges, Fuller, 2012).</p>														<h5>Hallazgos Claves</h5>														<p>Los participantes en Abriendo Puertas / Opening Doors mostraron aumentos significativos en todas las áreas de la evaluación, de moderados a grandes efectos:</p>														<ul class="a">						<li>Los padres demostraron un incremento significativo en su conocimiento del desarrollo del lenguaje y la alfabetización , en el desarrollo socio-emocional , en el desarrollo de la salud y la preparación para la escuela.</li><li>Padres demostraron aumento notable en el conocimiento de sus derechos como padre y los derechos de sus hijos en la escuela.</li><li>Los padres reportaron un incremento significativo en su auto-confianza en sus habilidades como padres, preparar a sus hijos para la escuela y abogar en su favor.</li>							</ul>														<p>								<a href="apdocs/apne.pdf">Pulse aquí para obtener el reporte completo</a>							</p>				</div> <!-- end textbox -->												<!-- LEFT PANE				====================================== -->															<div class="two-thirds column alpha">								<!-- AP IN THE NEWS  -->										<div name="AP IN THE NEWS" class="add-bottom">											<h5 class="ruled add-bottom google red-orange edit-txt" id="n4">AP en las Noticias</h5>																					<div class="textBox edit" id="n5"><ul>
	<li>
		<a href="http://ap-od.org/apdocs/wsj.pdf">WSJ: &quot;Hispanics Get Help Giving Their Kids a Boost</a></li>
	<li>
		<a href="http://ap-od.org/apdocs/poder.pdf">Poder: Bridging the Hispanic Achievement Gap</a></li>
	<li>
		<a href="http://ap-od.org/apdocs/ztt.pdf">Zero to Three: Beyond a Haircut, Lunch&nbsp;Pale, and New&nbsp;Shoes</a></li>
	<li>
		<a href="http://ap-od.org/apdocs/EdSource.pdf">Edsource: Parenting classes tailored for Latino families show promise in closing the achievment gap</a></li>
	<li>
		<a href="http://ap-od.org/apdocs/abqj.pdf">ABQ Journal</a></li>
	<li>
		<a href="http://ap-od.org/apdocs/bspot.pdf">Bright Spots</a></li>
</ul>
<ul class="a">
	<li>
		<a href="http://www.hfrp.org/publications-resources/browse-our-publications/parents-as-agents-of-change?utm_source=Authors&amp;utm_medium=email&amp;utm_term=leading_gutierrez&amp;utm_campaign=FINE2013Sept">Harvard Family Research Project: Parents&nbsp;as Agents of Change</a></li>
	<li>
		<a href="http://www.hfrp.org/publications-resources/browse-our-publications/padres-de-familia-como-agentes-de-cambio?utm_source=Authors&amp;utm_medium=email&amp;utm_term=leading_spanish&amp;utm_campaign=FINE2013Sept">Harvard Family Research Project: Padres&nbsp;de&nbsp;Familia como Agentes de Cambio</a></li>
	<li>
		<a href="http://metrolatinousa.com/2014/02/26/mas-padres-se-involucran-en-la-educacion-de-sus-hijos/"><span style="font-family: arial, sans-serif; font-size: 13px;">Padres de familia se involucran en la educaci&oacute;n de sus hijos | Metrolatino USA</span></a></li>
</ul>
</div> <!-- end textbox -->											</div> <!-- end AP in the NEWS -->									</div> <!-- end two-third column -->																<!-- RIGHT PANE 				====================================== -->								<div class="one-third column omega add-bottom">										<!-- ENDORSEMENTS -->														<h5 class="ruled add-bottom google purple  edit-txt" id="n6">Respaldo</h5>					<div class="textBox add-bottom edit" id="n7">						<ul class="style2">													<li><a href="apdocs/pca.pdf">Partnership for Community Action</a></li>														<li><a href="apdocs/denver.pdf">City of Denver</a></li>														<li><a href="apdocs/f5sf.pdf">First 5 San Francisco</a></li>														<li><a href="apdocs/f5c.pdf">First 5 Caleveras</a></li>													<li><a href="apdocs/gs.pdf">Good Samaritan</a></li>													<li> <a href="apdocs/wee3.pdf">WestEd E3 Institute</a></li>							<li><a href="apdocs/childfocus.pdf">Child Focus Inc. Cincinatti</a></li>							<li><a href="apdocs/enlance.pdf">Enlance</a></li>							<li><a href="apdocs/latinopolicy.pdf">Latino Policy Forum</a></li>							<li><a href="apdocs/lausd.pdf">Los Angelas Unified School District</a></li>							<li><a href="apdocs/naccra.pdf">NACCRA</a></li>						</ul>					</div> <!-- textbox -->														</div><!-- end one third column -->								<div class="sixteen columns add-bottom alpha">					<ul class="bxslider" >						<li><img src="images/impact/5.jpg" title="Parent Graduation in Lennox, CA"></li>										<li><img src="images/impact/4.jpg" title="Parent Graduation in El Carrizo, Honduras"></li>						<li><img src="images/impact/2.jpg" title="Parent Graduation in Las Cruces, NM"></li>						<li><img src="images/impact/1.jpg" title=""></li>						<li><img src="images/impact/3.jpg" title=""></li>							</ul>				</div> 												</div> <!-- end sixteen column -->							</div><!-- *** end container -->				<?php include('inc/esfooter.php'); ?>	<!-- End Document================================================== -->	<!--- Javascript  -->	<script src="js/jquery.min.js"></script>	<script src="js/jquery.bxslider.js"></script>		<!-- BXSLIDER.JS -->	<script type="text/javascript">		$(document).ready(function(){			$('.bxslider').bxSlider({				captions:true,				controls:true,				randomStart:false,			});		});	</script>			<!-- FLEXNAV.JS -->	<script type="text/javascript" src="js/jquery.flexnav.min.js"></script>	<script type="text/javascript">		$(".flexnav").flexNav();	</script> 		</body></html>	