<?php 	$pageTitle = "Resources &#9119; APOD";	$menuItem = "resources";	$spanishPage = "esresources.php";	include('inc/header.php'); ?>				  		<div class="container">			<div class="sixteen columns">					<h5 class="ruled remove-bottom google red-orange center edit-txt" id="n0">RESOURCES</h5>										<!-- Pledge Cards -->					<ul class="bxslider add" style="padding-bottom: 10px;">						<li><img src="images/parentpledgees.jpg"></li>						<li><img src="images/parentpledgeen.jpg"></li>					</ul>			</div> <!-- end 16 -->			<div class="sixteen columns add-bottom purple edit" id="n1">					<div class="four columns alpha">					<h2 class=" ruled remove-bottom google purple"> Pledge Cards</h2>				</div>				<div class="twelve columns omega purple textBox">					<p>						<strong>Abriendo Puertas/Opening Doors Parent Reading Pledge Card</strong><br> in <a href="apdocs/campen.pdf"><u><span style="color: white;">English</span></u></a> and <a href="apdocs/campes.pdf"><u><span style="color: white;"> Spanish</span></u></a> to encourage parents to make a commitment of reading more with their children at home.<br>					</p>				</div>			</div> <!-- end 16 -->			<!--MORE Resources Header			================================================== -->									<div class="sixteen columns add-bottom">									<div name="AP IN THE NEWS" class="dropshadowOrange">											<h5 class="ruled remove-bottom google red-orange center edit-txt" id="n2">MORE RESOURCES</h5>																					<div class="textBox white edit" id="n3"><ul class="a" id="resourcebox">
	<li>
		<a href="http://www.firstbook.org/"><strong><u><span style="color: blue;">First Book</span></u></strong></a> provides access to new books for children in need. To date, First Book has distributed more than 100 million books and educational resources to programs and schools serving children from low-income families throughout the United States and <a href="http://www.firstbookcanada.org/"><u><span style="color: blue;">Canada</span></u></a>. First Book is transforming the lives of children in need and elevating the quality of education by making new, high-quality books available on an ongoing basis.</li>
	<li>
		<strong><a href="http://www.first5kids.org/homepage/kindergarten" target="_blank">Kindergarten Readiness</a></strong> - FIRST 5 Santa Clara County and the Partnership for School Readiness have created an essential Parent Handbook that gives straightforward tips for families to get ready for school.</li>
	<li>
		<strong>California - 10 Questions to Ask Your School District about Fair School Funding / 10 Preguntas Para Hacerle A Su Distrito Escolar Sobre LCFF</strong> in <a href="http://www.calendow.org/uploadedFiles/10Q_LCFF_English.pdf"><u><span style="color: blue;">English</span></u></a> and <a href="http://www.calendow.org/uploadedFiles/10Q_LCFF_Spanish_2R.pdf"> <u><span style="color: blue;">Spanish</span></u></a></li>
	<li>
		<a href="http://www.choosemyplate.gov/"><strong><u><span style="color: blue;">MyPlate</span></u></strong></a> illustrates the five food groups that are the building blocks for a healthy diet using a familiar image&mdash;a place setting for a meal. Before you eat, think about what goes on your plate or in your cup or bowl.<a href="http://www.choosemyplate.gov/en-espanol.html"><strong><u>Mi Plato En Espanol</u></strong></a></li>
	<li>
		<a href="http://www.letsmove.gov/about"><strong><u><span style="color: blue;">Let&rsquo;s Move!</span></u></strong></a> is a comprehensive initiative, launched by the First Lady, dedicated to solving the problem of obesity within a generation, so that children born today will grow up healthier and able to pursue their dreams. <a href="http://www.letsmove.gov/en-espanol"><strong><u>Let&rsquo;s Move! En Espa&ntilde;ol</u></strong> </a></li>
	<li>
		<strong><a href="http://gradelevelreading.net/healthy-readers-resources-guides" target="_blank">Growing Healthy Readers: Taking Action to Support the Health Determinants of Early School Success</a></strong> The <i>Growing Healthy Readers </i>series was developed by the Campaign&rsquo;s <i>Healthy Readers </i>team and will help community- and state-level coalitions determine how to take action on priority issues that affect children&rsquo;s health and learning.</li>
	<li>
		<a href="http://www.attendanceworks.org/wordpress/wp-content/uploads/2010/06/Attendance_1PG_0911_FINAL.pdf"><strong><u><span style="color: blue;">Attendance Works</span></u></strong> Help Your Child Succeed in School: Build the Habit of Good Attendance Early</a> <a href="http://www.attendanceworks.org/wordpress/wp-content/uploads/2010/06/Attendance_ESP_1PG_1011_v1.pdf"><strong><u><span style="color: blue;">Attendance Works En Espanol</span></u></strong></a></li>
	<li>
		<strong><a href="http://www.colorincolorado.org/about/"><u><span style="color: blue;">Color&iacute;n Colorado</span></u></a></strong> is a free web-based service that provides information, activities and advice for educators and Spanish-speaking families of English language learners (ELLs). <a href="http://www.colorincolorado.org/sobre/"><strong><u><span style="color: blue;">Color&iacute;n Colorado En Espanol</span></u></strong> </a></li>
	<li>
		<strong><a href="http://toosmall.org/About"><span style="color: blue;">Too Small to Fail</span></a></strong> aims to help parents and businesses take meaningful actions to improve the health and well-being of children ages zero to five, so that more of America&rsquo;s children are prepared to succeed in the 21st century.</li>
	<li>
		<strong><a href="http://gradelevelreading.net/"><span style="color: blue;">The Campaign for Grade-Level Reading </span></a></strong> The Campaign is a collaborative effort by foundations, nonprofit partners, states and communities across the nation to ensure that more children in low-income families succeed in school and graduate prepared for college, a career, and active citizenship. The Campaign focuses on the most important predictor of school success and high school graduation&mdash;grade-level reading by the end of third grade.The Campaign for Grade-Level Reading and the 140+ communities working with the Campaign are dedicated to narrowing the gap between children from low-income families and their more affluent peers. This video shows why that gap occurs and how we can close it. - <strong><a href="http://youtu.be/52KuhCpiOUE" target="_blank">Statisticks Lottery</a></strong></li>
	<li>
		<strong><a href="http://readaloud.org/index.html">Read Aloud 15 MINUTES</a></strong> is a non-profit organization that is working to make reading aloud every day for at least 15 minutes the new standard in child care.</li>
	<li>
		<strong><a href="http://readyrosie.com/">ReadyRosie</a></strong> - Ready for school. Ready for the world.</li>
	<li>
		<strong><a href="https://www.nhsa.org/initiatives_and_partnerships/abriendo_puertas__opening_doors_network/other_resources/framework"><span style="color: blue;">Head Start Parent and Family Engagement Framework and the Head Start Child Development and Early Learning Framework</span></a></strong></li>
	<li>
		<strong><a href="http://www.nwlc.org/tax-credits-outreach"><span style="color: blue;">Tax Credits Outreach</span></a></strong></li>
	<li>
		<strong><a href="http://www.intercambioweb.org/"><span style="color: blue;">Intercambio Uniting Communities </span></a></strong>is a non-profit organization whose mission is to build understanding, respect and friendship across cultures through educational and intercultural opportunities.</li>
</ul>
</div> <!-- end textbox -->											</div> <!-- end AP in the news -->			</div> <!-- end sixteen -->					</div>			<!-- Footer v3	================================================== --><?php include('inc/footer.php'); ?><!-- End Document================================================== -->	<!--- Javascript  -->	<script src="js/jquery.min.js"></script>	<script src="js/jquery.bxslider.js"></script>		<!-- bxslider. I'm trying it in a new position to see if loading times improve -->	<script type="text/javascript">		$(document).ready(function(){			$('.bxslider').bxSlider({				slideWidth: 3000,			    minSlides: 2,			    maxSlides: 2,			    slideMargin: 0,			    moveSlides: 0,			    auto: false,			});		});	</script>	<!-- FlexNav -->	<script type="text/javascript" src="js/jquery.flexnav.min.js"></script>	<script type="text/javascript">		$(".flexnav").flexNav();	</script>	</body></html>